# Generated by Django 5.2.2 on 2025-06-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
